### ISSUE TITLE
Textarea can not refocus after clicking on address bar/developer tools on firefox

### ISSUE THREAD

**Issue by arrizalamin** [Soreine/water-writing#14]
This is not a problem in chrome, but it is in firefox 56. I think listen click event on `#wall` element to refocus, instead of listen onBlur event on textarea would fix this issue.

**Comment by Soreine** [comment]
Thanks. I listened to click events on `#wall` as well and refocus.
Listening to `onBlur` ensures that the textarea never loses focus.

**Comment by Soreine** [comment]
@arrizalamin I'm glad you stumbled on that project. I'll be glad to hear your advices and suggestions. How did you came across the project ?
