### ISSUE TITLE
Create script to deploy prototype on gh-pages

### ISSUE THREAD

**Issue by Soreine** [Soreine/water-writing#2]
For now, and as long as the app is meant to be a single user experience, we are able to build it and deploy it to gh-pages.

Would be nice to have a script that does that.

**Comment by mpizenberg** [comment]
Je ne suis pas fan du tout du fait de commit des fichiers compilés (main.js) dans master. A la base, je n'aime pas le principe de la branche gh-pages (puisque de facto tu commit des fichiers compilés). Je préfère largement le système de gitlab ou les gitlab pages sont le résultat d'un build (comme des tests CI). Mais je ne crois pas que ce soit possible avec github (est-ce possible ?).
Qu'est-ce que vous pensez d'un script plutot de la forme :
```shell
build ... # build files into build folder (dist/ for example)
cd dist/ # qui est un sous dossier ignoré par git correspondant au même dépot mais à la branche gh-pages
git add -f .
git commit -m "Deploy gh-pages"
git push
```

**Comment by Soreine** [comment]
Hmm oui.

On Sat, Mar 4, 2017 at 5:37 AM, Matthieu Pizenberg <notifications@github.com
