### ISSUE TITLE
Input stops working sometimes

### ISSUE THREAD

**Issue by Soreine** [Soreine/water-writing#9]
Getting this bug this since https://github.com/Soreine/water-writing/commit/49e8c3f9b717f32c1ff1084494cb3154cca07eeb approximately...
Cannot reproduce reliably.
Input starts working again after some time, for unknown reason.

**Comment by mpizenberg** [comment]
Weird, I did not experienced it yet on chromium 56 - linux.

**Comment by Soreine** [comment]
Could not reproduce again...
